import React, { useState, useEffect, useContext } from 'react';
import axios from 'axios';
import { AuthContext } from '../context/AuthContext';
import { FileText, Download, Filter, AlertCircle } from 'lucide-react';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const NCC_YEARS = ['All Years', '1st Year', '2nd Year - B Certificate', '3rd Year - C Certificate'];

const Reports = () => {
  const { user } = useContext(AuthContext);
  const [records, setRecords] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [year, setYear] = useState('All Years');
  const [status, setStatus] = useState('All');

  const fetchRecords = async () => {
    setLoading(true); setError('');
    try {
      const params = {};
      if (fromDate) params.fromDate = fromDate;
      if (toDate) params.toDate = toDate;
      if (year !== 'All Years') params.year = year;
      const { data } = await axios.get('/api/attendance', {
        params,
        headers: { Authorization: `Bearer ${user.token}` },
      });
      let filtered = data;
      if (status !== 'All') filtered = data.filter(r => r.status === status);
      setRecords(filtered);
    } catch (err) {
      setError('Failed to fetch attendance records.');
    } finally {
      setLoading(false);
    }
  };

  const exportExcel = () => {
    const rows = records.map((r, i) => ({
      'S.No.': i + 1,
      'Date': new Date(r.date).toLocaleDateString('en-IN'),
      'Reg. No.': r.cadetId?.regNo || '',
      'Cadet Name': r.cadetId?.name || '',
      'NCC Year': r.cadetId?.year || '',
      'Status': r.status,
      'Marked By': r.markedBy?.name || '',
    }));
    const ws = XLSX.utils.json_to_sheet(rows);
    ws['!cols'] = [{ wch: 6 }, { wch: 14 }, { wch: 10 }, { wch: 22 }, { wch: 28 }, { wch: 10 }, { wch: 18 }];
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Attendance');
    XLSX.writeFile(wb, `NCC_Attendance_Report_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('NATIONAL CADET CORPS', 105, 18, { align: 'center' });
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('CADET ATTENDANCE REPORT', 105, 26, { align: 'center' });
    doc.setFontSize(9);
    doc.text(`NCC Year: ${year}`, 14, 36);
    if (fromDate || toDate) {
      doc.text(`Date Range: ${fromDate || 'All'} to ${toDate || 'All'}`, 14, 42);
    }
    doc.text(`Generated By: ${user.name}`, 14, 48);
    doc.text(`Generated Date: ${new Date().toLocaleDateString('en-IN')}`, 14, 54);

    autoTable(doc, {
      startY: 60,
      head: [['S.No.', 'Date', 'Reg. No.', 'Name', 'NCC Year', 'Status', 'Marked By']],
      body: records.map((r, i) => [
        i + 1,
        new Date(r.date).toLocaleDateString('en-IN'),
        r.cadetId?.regNo || '',
        r.cadetId?.name || '',
        r.cadetId?.year || '',
        r.status,
        r.markedBy?.name || '',
      ]),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: [44, 85, 48], textColor: 255, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [245, 248, 245] },
    });

    doc.save(`NCC_Attendance_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="p-6">
      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 bg-[#2c5530] text-white rounded-xl flex items-center justify-center">
          <FileText size={20} />
        </div>
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Reports</h1>
          <p className="text-sm text-gray-500">Generate and export attendance reports</p>
        </div>
      </div>

      {/* Filter Card */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-5 mb-5">
        <h2 className="font-semibold text-gray-700 mb-4 flex items-center gap-2"><Filter size={16}/>Filter Records</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
          <div>
            <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">From Date</label>
            <input type="date" value={fromDate} onChange={e => setFromDate(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-2 focus:ring-[#2c5530]" />
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">To Date</label>
            <input type="date" value={toDate} onChange={e => setToDate(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-2 focus:ring-[#2c5530]" />
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">NCC Year</label>
            <select value={year} onChange={e => setYear(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-2 focus:ring-[#2c5530] bg-white">
              {NCC_YEARS.map(y => <option key={y}>{y}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-xs font-semibold text-gray-500 uppercase tracking-wider mb-1">Status</label>
            <select value={status} onChange={e => setStatus(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm outline-none focus:ring-2 focus:ring-[#2c5530] bg-white">
              <option>All</option>
              <option>Present</option>
              <option>Absent</option>
            </select>
          </div>
        </div>
        <div className="flex flex-wrap gap-3">
          <button onClick={fetchRecords} className="flex items-center gap-2 px-5 py-2.5 bg-[#2c5530] text-white text-sm font-semibold rounded-lg hover:bg-[#1b381e] transition-colors">
            <Filter size={15} /> Generate Report
          </button>
          {records.length > 0 && (
            <>
              <button onClick={exportExcel} className="flex items-center gap-2 px-5 py-2.5 bg-emerald-600 text-white text-sm font-semibold rounded-lg hover:bg-emerald-700 transition-colors">
                <Download size={15} /> Export Excel
              </button>
              <button onClick={exportPDF} className="flex items-center gap-2 px-5 py-2.5 bg-red-600 text-white text-sm font-semibold rounded-lg hover:bg-red-700 transition-colors">
                <Download size={15} /> Export PDF
              </button>
            </>
          )}
        </div>
      </div>

      {/* Summary */}
      {records.length > 0 && (
        <div className="grid grid-cols-3 gap-4 mb-5">
          <div className="bg-white border border-gray-200 rounded-xl p-4 text-center shadow-sm">
            <p className="text-2xl font-bold text-gray-900">{records.length}</p>
            <p className="text-xs text-gray-500 uppercase font-semibold mt-1">Total Records</p>
          </div>
          <div className="bg-green-50 border border-green-200 rounded-xl p-4 text-center shadow-sm">
            <p className="text-2xl font-bold text-green-700">{records.filter(r => r.status === 'Present').length}</p>
            <p className="text-xs text-green-600 uppercase font-semibold mt-1">Present</p>
          </div>
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-center shadow-sm">
            <p className="text-2xl font-bold text-red-600">{records.filter(r => r.status === 'Absent').length}</p>
            <p className="text-xs text-red-500 uppercase font-semibold mt-1">Absent</p>
          </div>
        </div>
      )}

      {error && <div className="flex items-center gap-2 bg-red-50 text-red-700 border border-red-200 rounded-lg p-3 mb-4 text-sm"><AlertCircle size={14}/>{error}</div>}

      {/* Table */}
      <div className="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-50 border-b border-gray-200">
              <tr>
                {['S.No.', 'Date', 'Reg. No.', 'Cadet Name', 'NCC Year', 'Status', 'Marked By'].map(h => (
                  <th key={h} className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {loading ? (
                <tr><td colSpan={7} className="py-10 text-center text-gray-400">Loading...</td></tr>
              ) : records.length === 0 ? (
                <tr><td colSpan={7} className="py-10 text-center text-gray-400">
                  Apply filters above and click <strong>Generate Report</strong>.
                </td></tr>
              ) : records.map((r, idx) => (
                <tr key={r._id} className="hover:bg-gray-50">
                  <td className="px-4 py-3 text-gray-500">{idx + 1}</td>
                  <td className="px-4 py-3 text-gray-700">{new Date(r.date).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' })}</td>
                  <td className="px-4 py-3 font-mono font-semibold text-gray-800">{r.cadetId?.regNo}</td>
                  <td className="px-4 py-3 font-medium text-gray-900">{r.cadetId?.name}</td>
                  <td className="px-4 py-3 text-xs text-gray-500">{r.cadetId?.year}</td>
                  <td className="px-4 py-3">
                    <span className={`px-2.5 py-1 rounded-full text-xs font-bold ${r.status === 'Present' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>{r.status}</span>
                  </td>
                  <td className="px-4 py-3 text-gray-500">{r.markedBy?.name || '—'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Reports;
